### ISSUE TITLE
Hello, can i make that with new structure ? , im need to add multiple partners at same line !

### ISSUE THREAD

**Issue by hamza-ahmed** [Team-Blox/TreeView#77] opened 2021-02-23 18:23 UTC

**Comment by GregorBlock** [comment] 2021-03-14 12:48
Duplicate of #61

**Comment by GregorBlock** [comment] 2021-04-14 09:48
I'm closing this issue due to inactivity. If you have further input on the issue, don't hesitate to reopen this issue or post a new one.

**Closed as completed by GregorBlock** 2021-04-14 09:48 UTC
