### ISSUE TITLE
Why this graphview dont have add child

### ISSUE THREAD

**Issue by williamwong9090** [Team-Blox/TreeView#17] opened 2018-09-19 07:51 UTC
May i know why this treeview library dont had contain addchild and setRootNode function ?

**Comment by GregorBlock** [comment] 2018-09-19 08:24
Duplicate of #16

**Comment by GregorBlock** [comment] 2018-09-19 08:30
This library is in an early stage of development. The method addNode(Node...) will be added in the next release.

**Comment by williamwong9090** [comment] 2018-09-25 10:18
Hi Sir


Sorry for disturbing . May i know when you will release update on Graph View ?


Thank



Cc: williamwong9090; Author
Subject: Re: [Team-Blox/GraphView] Why this graphview dont have add child (#17)


This library is in an early stage of development. The method addChild(Node) will be added in the next release.

**Comment by GregorBlock** [comment] 2018-09-25 14:21
as we are still working on the zoom feature, probably during the week.

**Closed as completed** 2018-10-22 14:32 UTC
Labels: duplicate
