### ISSUE TITLE
Zoom problem when node is added dynamically

### ISSUE THREAD

**Issue by karankharecha** [Team-Blox/TreeView#30] opened 2019-01-09 11:35 UTC
When I add the node dynamically, it doesn't zoom out. Is there any way to zoom out and fit, all nodes of a tree, in the screen when it gets added?

**Comment by GregorBlock** [comment] 2019-01-09 11:59
Duplicate of #22

**Comment by thuijssoon** [comment] 2020-01-21 07:46
I have resolved this by setting a transformation like this:

```
gvGraph.getEngine().setTransformation(ZoomApi.TRANSFORMATION_CENTER_INSIDE, Gravity.CENTER);
```

and then adding a `ZoomEngine.Listener` to the graph and listen for an update before you make the change like this:

```
            mListener = new ZoomEngine.Listener() {
                @Override
                public void onUpdate(@NotNull ZoomEngine zoomEngine, @NotNull Matrix matrix) {
                    Handler handler = new Handler();
                    handler.postDelayed(() -> gvGraph.zoomTo(1f, false), 10);
                    gvGraph.getEngine().removeListener(mListener);
                }

                @Override
                public void onIdle(@NotNull ZoomEngine zoomEngine) {

                }
            };
            gvGraph.getEngine().addListener(mListener);
```

Somehow it doesn't work on idle, nor does it work without a delay... Setting the zoom to `1f` when using the transformation causes the entire graph to be visible. Make sure you add the listener just before adding the new node.

I hope this helps.

**Comment by GregorBlock** [comment] 2020-07-03 12:55
Closed. Zoomengine is not longer part of graphview.

**Closed as completed by GregorBlock** 2020-07-03 12:55 UTC
Labels: duplicate
